### PR TITLE
*: update submodules

### PR DESCRIPTION
**Pull request by tabokie**
Also cherry-pick #705 

Signed-off-by: tabokie <xy.tao@outlook.com>

### CODE REVIEW

**Comment by tabokie** [comment]
@waynexia Please use this branch (tikv-6.1). We upgraded RocksDB in master branch and it is still experimental.

**Comment by waynexia** [comment]
Looks like that branch doesn't contain `ffd01b8dfb7112f39468fbaad780b73d663d2bd9`. Appreciate it if we can do a cherry-pick

**Comment by tabokie** [comment]
It will be when https://github.com/tikv/titan/pull/254 is merged.

**Comment by tabokie** [comment]
Ping @Connor1996

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
