### PR TITLE
Expose rocksdb dictionary compression options setter

### PR DESCRIPTION
**Pull request by AngleNet**
Expose dictionary compression options for rocksdb to Tikv. So we could introduce dictionary compression to Tikv to relieve the compression issue. It's part of work [Issue 8635](https://github.com/tikv/tikv/issues/8635).

Issue Number: https://github.com/tikv/tikv/issues/8635

### CODE REVIEW

**Review by yiwu-arbug — APPROVED** [review]
LGTM. Go ahead with TiKV change.

**Comment by Rustin-Liu** [comment]
@yiwu-arbug Manually added.

The current bot does not yet support cross-repository, it will be supported in the future.

**Comment by tabokie** [comment]
@AngleNet Could you please speed up the TiKV change related to this PR? You don't have to wait on the full implementation to be ready. This interface change is blocking TiKV from updating `rust-rocksdb`.

**Pull request merged**
