### PR TITLE
librocksdb_cloud_sys: link dependencies and complete binding

### PR DESCRIPTION
**Pull request by de-sh**
To correctly build cloud features with AWS-CPP-SDK

### Related PRs
- tikv/rocksdb#186
- tikv/rocksdb#188

### CODE REVIEW

**Comment by de-sh** [comment]
@yiwu-arbug can you take a look at this?

**Comment by de-sh** [comment]
Considering the CI build error coming up, we have to link the aws-cpp-sdk

**Comment by de-sh** [comment]
I am unsure why I am no longer able to push to this PR

**Comment by yiwu-arbug** [comment]
@de-sh looks like your repository is deleted. you can send a new PR. thanks.

**Pull request closed without merging**
