### PR TITLE
rocksdb: Allow applying `CompactionFilter` outside of compaction (facebook#8243)

### PR DESCRIPTION
**Pull request by ti-srebot**
update rocksdb to include tikv/rocksdb#243 for master
### Release note
- No release note

### CODE REVIEW

**Comment by MrCroxx** [comment]
@Connor1996 Please help merge this pr, it automatically updated submodule `rorkcsdb`.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by Connor1996** [comment]
@MrCroxx I don't have admin authority to merge in this repo

**Comment by MrCroxx** [comment]
@tabokie PTAL

**Pull request merged**
