### PR TITLE
update rocksdb hash

### PR DESCRIPTION
**Pull request by hunterlxt**
Signed-off-by: TXXT <hunterlxt@live.com>

### CODE REVIEW

**Comment by BusyJay** [comment]
What's purpose?

**Comment by hunterlxt** [comment]
@BusyJay  to use encryption perf_context api  https://github.com/tikv/rocksdb/pull/158

**Comment by yiwu-arbug** [comment]
We still miss https://github.com/tikv/rocksdb/pull/166. And @sre-bot is supposed to send PR atomatically.

**Comment by overvenus** [comment]
https://github.com/tikv/rocksdb/pull/166 is merged, please update again, thanks!

**Comment by hunterlxt** [comment]
Updated hash. PTAL @overvenus @yiwu-arbug @Connor1996

**Comment by overvenus** [comment]
Cool, LGTM

**Comment by Connor1996** [comment]
There is already a PR to update it, see https://github.com/tikv/rust-rocksdb/pull/476.
It will be merged automatically when the CI is finished

**Comment by Connor1996** [comment]
> We still miss [tikv/rocksdb#166](https://github.com/tikv/rocksdb/pull/166). And @sre-bot is supposed to send PR automatically.

@yiwu-arbug it doesn't miss the update PR, see #476

**Comment by Connor1996** [comment]
> @BusyJay to use encryption perf_context api [tikv/rocksdb#158](https://github.com/tikv/rocksdb/pull/158)

The auto-update https://github.com/tikv/rust-rocksdb/pull/456 for the tikv/rocksdb#158 is not merged due to bug. Now the sre-bot is working correctly, so let's close this PR and let the bot to finish the work.

**Comment by hunterlxt** [comment]
LGTM

**Pull request closed without merging**
